language: generic
sudo: required
dist: trusty
cache:
  directories:
    - CMakeFiles/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
            - p7zip
            - cmake
            - cmake-data
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - libglew-dev
            - libsdl2-dev
            - libsdl2-image-dev
install:
  - sudo ln -s /usr/bin/g++-7 /usr/bin/g++ -f
  - |
    git clone https://github.com/rpclib/rpclib.git
    cd ./rpclib
    cmake . -DBUILD_SHARED_LIBS=ON && make -j8
    sudo make install 
    cd ..
script:
  - cmake .
  - make -j8
